cubes:
  - name: candidate_application
    sql_table: '"CandidateApplication"'
    joins:
      - name: candidate_profile
        sql: '{CUBE}."candidateProfileId" = {candidate_profile}.id'
        relationship: many_to_one
      - name: company
        sql: '{CUBE}."companyId" = {company}.id'
        relationship: many_to_one
      - name: job_listing
        sql: '{CUBE}."jobListingId" = {job_listing}.id'
        relationship: many_to_one
      - name: template_stage
        sql: '{CUBE}."templateStageId" = {template_stage}.id'
        relationship: many_to_one
      - name: job_opening
        sql: '{CUBE}.id = {job_opening}."filledByApplication"'
        relationship: one_to_many
      - name: candidate_application_status
        sql: '{CUBE}.id = {candidate_application_status}."candidateApplicationId"'
        relationship: one_to_many
    measures:
      - name: count
        type: count
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: candidateprofileid
        sql: '{CUBE}."candidateProfileId"'
        type: number
      - name: applicationtype
        sql: '{CUBE}."applicationType"'
        type: string
      - name: applicationstatus
        sql: '{CUBE}."applicationStatus"'
        type: string
      - name: joblistingid
        sql: '{CUBE}."jobListingId"'
        type: number
      - name: templatestageid
        sql: '{CUBE}."templateStageId"'
        type: number
      - name: applicationtimestamp
        sql: '{CUBE}."applicationTimestamp"'
        type: time
      - name: companyid
        sql: '{CUBE}."companyId"'
        type: number
      - name: viewedprofile
        sql: '{CUBE}."viewedProfile"'
        type: boolean
      - name: matchscore
        sql: '{CUBE}."matchScore"'
        type: number
      - name: lastupdatedstatusat
        sql: '{CUBE}."lastUpdatedStatusAt"'
        type: time
      - name: applicationcreationtype
        sql: '{CUBE}."applicationCreationType"'
        type: string
      - name: interviewscheduling
        sql: '{CUBE}."interviewScheduling"'
        type: string
      - name: viewedat
        sql: '{CUBE}."viewedAt"'
        type: time
      - name: createdat
        sql: '{CUBE}."createdAt"'
        type: time
      - name: updatedat
        sql: '{CUBE}."updatedAt"'
        type: time
      - name: appliedat
        sql: '{CUBE}."appliedAt"'
        type: time
      - name: deleted
        sql: '{CUBE}."deleted"'
        type: time
