cubes:
  - name: candidate_application_status
    sql_table: candidate_application_status
    joins:
      - name: job_listing
        sql: "{CUBE}.job_listing_id = {job_listing}.id"
        relationship: many_to_one
      - name: candidate_application
        sql: "{CUBE}.candidate_application_id = {candidate_application}.id"
        relationship: many_to_one
      - name: scalis_user
        sql: "{CUBE}.scalis_user_id = {scalis_user}.id"
        relationship: many_to_one
    measures:
      - name: count
        type: count
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: scalisuserid
        sql: "{CUBE}.scalis_user_id"
        type: number
      - name: joblistingid
        sql: "{CUBE}.job_listing_id"
        type: number
      - name: candidateapplicationid
        sql: "{CUBE}.candidate_application_id"
        type: number
      - name: campaignid
        sql: "{CUBE}.campaign_id"
        type: number
      - name: source
        sql: "{CUBE}.source"
        type: string
      - name: startedat
        sql: "{CUBE}.started_at"
        type: time
      - name: completedat
        sql: "{CUBE}.completed_at"
        type: time
