cubes:
  - name: custom_candidate_application_field_value
    sql_table: custom_candidate_application_field_value
    joins:
      - name: company_user
        sql: '{CUBE}.company_user_id = {company_user}.id'
        relationship: many_to_one
      - name: custom_candidate_application_field
        sql: '{CUBE}.custom_candidate_application_field_id =
          {custom_candidate_application_field}.id'
        relationship: many_to_one
      - name: candidate_application
        sql: '{CUBE}.candidate_application_id = {candidate_application}.id'
        relationship: many_to_one
    measures:
      - name: count
        type: count
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: customcandidateapplicationfieldid
        sql: '{CUBE}.custom_candidate_application_field_id'
        type: number
      - name: candidateapplicationid
        sql: '{CUBE}.candidate_application_id'
        type: number
      - name: value
        sql: '{CUBE}.value'
        type: string
      - name: companyuserid
        sql: '{CUBE}.company_user_id'
        type: number
      - name: createdat
        sql: '{CUBE}.created_at'
        type: time
      - name: updatedat
        sql: '{CUBE}.updated_at'
        type: time
